image: docker:latest
variables:
 DOCKER_DRIVER: overlay2 
 DOCKER_HOST: tcp://docker:2375/
services:
  - docker:dind
stages:
  - build-push
  - deploy

build:
  stage: build-push
  script:
    - docker build -t "303247004675.dkr.ecr.eu-west-1.amazonaws.com/zen-hr:front" .
    - docker push 303247004675.dkr.ecr.eu-west-1.amazonaws.com/zen-hr:front
  only:
      - Pipeline

before_script:
  - apk add --update python py-pip python-dev
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region eu-west-1)

deploy:
  stage: deploy
  script: 
    - aws s3 cp eb/hr.zip s3://$AWS_S3_BUCKET/

    - aws elasticbeanstalk create-application-version --application-name zen-hr --version-label $CI_CONCURRENT_ID --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key='hr.zip' --region eu-west-1

    - aws elasticbeanstalk update-environment --environment-name ZenHr-env --version-label $CI_CONCURRENT_ID --region eu-west-1
  
  only:
      - Pipeline
  
